image: node:6
clone:
  depth: full
pipelines:
  default:
  - step:
      name: Deploy to Heroku
      deployment: test
      script:
        #- git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
        #- npm install
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
        - composer install
        - php artisan migrate

